import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MotivateMe!</h1>
        <Button>Video Generator</Button>
        <Button>Explore Events</Button>
      </main>
    </div>



  )
}
